### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by spinecone** [CSC322-Grinnell/anti-racism-library#13]
Based on Prajita's figma design. Look into bootstrap or similar rather than implementing css from scratch (https://getbootstrap.com/).

**Comment by Coolshreshtha** [comment]
There doesn't seem to be a clear automatic way to convert figma css to bootstrap. Here's a promising alternative consisting of ui things https://demos.creative-tim.com/material-kit-figma/presentation.html that may work

**Comment by athaichi** [comment]
-- add admin only actions to admin drop down menu (page for editing library)  should see: [add a resource, edit a resource, delete a resource]
