### ISSUE TITLE
Design prototyping

### ISSUE THREAD

**Issue by spinecone** [CSC322-Grinnell/anti-racism-library#4]

**Comment by spinecone** [comment]
Consider tools like figma

**Comment by niraulap** [comment]
### DRAFT 1
Link to prototype: 
https://www.figma.com/proto/63UaNaHNfHPjV2CtdIQXbN/Anti-Racism-Library?node-id=1%3A2&scaling=min-zoom

Link to Figma working page: 
https://www.figma.com/file/63UaNaHNfHPjV2CtdIQXbN/Anti-Racism-Library?node-id=0%3A1

[](url)

**Comment by spinecone** [comment]
This can be closed as soon as these figma links are added to the readme or another docs page in the repo
