### ISSUE TITLE
Add ability to create and edit a library item from the UI

### ISSUE THREAD

**Issue by spinecone** [CSC322-Grinnell/anti-racism-library#6]
Since there's no user accounts yet, anyone can create or edit

**Comment by spinecone** [comment]
If you folks get done with this one before the end of the sprint, https://github.com/CSC322-Grinnell/anti-racism-library/issues/7 makes sense as a followup issue

**Comment by cvrkota** [comment]
We implemented the feature to add a library item to the database. We will put this story down while we work on #7, since we are thinking to implement "modify library item feature" on the page where the item is showing.
